version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    links:
      - db
      - elastic
    volumes:
      - ../sources:/var/www/html/magento2
  db:
    image: "mariadb:10.4"
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_ROOT_HOST: "%"
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
  elastic:
    image: "elasticsearch:7.17.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
